version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nodejs2022q2-network
    volumes:
      - nodejs2022q2-volume:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT}
    networks:
      - nodejs2022q2-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  nodejs2022q2-volume:
    name: nodejs2022q2-volume

networks:
  nodejs2022q2-network:
    name: nodejs2022q2-network
    driver: bridge
